### PR TITLE
Added web-component version of API

### PR DESCRIPTION
**Pull request by PixelsCommander**
Now you can do `<glsl-editor menu="false" canvas_size="100">FRAGMENT SHADER CODE...</glsl-editor>` for my blog this was an improvement since now article text and code are kept consistant. Same syntax will work for regular JS version `<div id='glslEditor'>FRAGMENT SHADER CODE</div> new glslEditor('#glslEditor')`

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Hi! thanks for the PR, could you explain what this improvement is about? thanks

**Comment by PixelsCommander** [comment]
Ah, I see, tags were hidden. Check it out now.

**Comment by patriciogonzalezvivo** [comment]
So is back compatible? I shouldn't need to change a thing on the book of shaders?

**Comment by PixelsCommander** [comment]
Yes, it is compatible. However always good to test on your test cases after
update.

2016-12-28 20:47 GMT+01:00 Patricio Gonzalez Vivo <notifications@github.com>
:

**Comment by patriciogonzalezvivo** [comment]
awesome! I will give it a try! thanks again!

**Comment by PixelsCommander** [comment]
Great! You are welcome!

**Comment by patriciogonzalezvivo** [comment]
@PixelsCommander, I have note that after this merge when you press on "☉ New" it creates a new tab, but copy the previous document. Could you check it. Thanks you

**Comment by PixelsCommander** [comment]
Ok, I see, will fix

2017-01-04 15:53 GMT+01:00 Patricio Gonzalez Vivo <notifications@github.com>
:

**Pull request merged**
