### PR TITLE
refactor: move to Vite, upgrade Electron

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
My git client didn't like the merge conflicts from #80, but upgrades/cleans up the toolchain. Also updated `FileSaver` to ESM.

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
Am I just working against @guidoschmidt with #80 and #81? Happy to close and defer to them for withstanding issues.

**Comment by guidoschmidt** [comment]
Oh yeah looks like we were both trying to fix glslEditor going different ways. I haven't used electron for like 5 or more so years and completly dropped it with my solution. Could still be nice to have the possibility to run glslEditor via elector, no? Maybe @patriciogonzalezvivo has some thoughts and wishes regarding that?

**Comment by guidoschmidt** [comment]
Ok, that was pretty easy to integrate @CodyJasonBennett. Nice work! Just merged your version into my fork:

https://github.com/guidoschmidt/glslEditor/commits/main

Thanks to vite and @CodyJasonBennett, we can easily run `npm run browser` or `npm run electron` (`yarn browser`/`yarn electron`) now 🙃. However I'd want to restructure the project in a better way, because now we have a vite config file with the electron plugin and the browser version just points vite to the `src/` folder with no config, which can be a bit misleading.

**Comment by CodyJasonBennett** [comment]
Continuing in #81.

**Pull request closed without merging**
