### PR TITLE
Fixing new tabs created with fragment shader from initial tab

### PR DESCRIPTION
**Pull request by PixelsCommander**
Fixed an issue addressed in comments to https://github.com/patriciogonzalezvivo/glslEditor/pull/14

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
THANKS AGAIN! : )

**Comment by PixelsCommander** [comment]
NP, thanks for this editor! Works great for my article. 

I would be very pleased if I have **any kind** of your comments on it. Starting from grammar and up to code review. The aim for article is to fill the gap between Web apps development and GLSL. It also refers your book as a relevant source of knowledge ;) http://pixelscommander.com/interactive-revolution/glsl-web-components-webgl/

**Comment by patriciogonzalezvivo** [comment]
Nice article! I will read it more carefully over the week and make comments : ) 

Related to the prev PR... I still experience the problem : / any thought?

**Comment by brucelane** [comment]
This article is great! This repo is great! You are both great!
Thank you very much!

**Comment by PixelsCommander** [comment]
Thanks Bruce! This is inspiring!

@patriciogonzalezvivo My steps for testing is:
1.Open index.html
2.It opens new editor with default shader
3.I remove Author, Title and change gl_FragColor to vec4(1.)
4.Then I click New and this opens new tab with default shader, not edited one.

Based on this looks like the problem is solved.

**Comment by PixelsCommander** [comment]
Uh, now I see. If I do it more times it is still reproducible.

**Pull request merged**
